import { useMemo } from "react";
import type { Recipe } from "../../engine/engine";
import { RecipeCanvas } from "./recipe-canvas";
import { cn } from "@/lib/utils";

const AVATAR_PALETTES: [string, string][] = [
  ["#7ac74f", "#3e7a2e"],
  ["#e0b040", "#a07820"],
  ["#d04848", "#8a2e2e"],
  ["#c8d0dc", "#5a6a7a"],
  ["#b070d0", "#6a3a8a"],
  ["#50b8c8", "#2a6a78"],
];

function hashName(name: string): number {
  let h = 2166136261 >>> 0;
  for (let i = 0; i < name.length; i++) {
    h = Math.imul(h ^ name.charCodeAt(i), 16777619) >>> 0;
  }
  return h;
}

/** Deterministic 8x8 identicon, generated by the spriteloom engine itself. */
export function avatarRecipe(username: string): Recipe {
  const h = hashName(username);
  const [c1, c2] = AVATAR_PALETTES[h % AVATAR_PALETTES.length]!;
  return {
    size: 8,
    name: `@${username}`,
    palette: { colors: ["#101010", c1, c2] },
    ops: [
      { op: "scatter", x: 1, y: 1, w: 3, h: 6, density: 0.55, seed: h, v: 1 },
      { op: "scatter", x: 1, y: 1, w: 3, h: 6, density: 0.28, seed: (h ^ 0x9e3779b9) >>> 0, v: 2 },
      { op: "mirror", axis: "x" },
    ],
  };
}

export function PixelAvatar({ username, size = 28, className }: { username: string; size?: number; className?: string }) {
  const recipe = useMemo(() => avatarRecipe(username), [username]);
  return (
    <RecipeCanvas
      recipe={recipe}
      pixel={Math.max(1, Math.round(size / 8))}
      title={`@${username}`}
      className={cn("border", className)}
    />
  );
}
