import { Bot, Download, FolderPlus, GitFork, Heart } from "lucide-react";
import type { CollectionItem, SpriteItem } from "../api";
import { RecipeCanvas } from "./recipe-canvas";
import { PixelAvatar } from "./pixel-avatar";
import { Tip } from "./tip";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardFooter } from "@/components/ui/card";
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuLabel,
  DropdownMenuSeparator,
  DropdownMenuTrigger,
} from "@/components/ui/dropdown-menu";
import { cn } from "@/lib/utils";

export function SpriteCard({
  sprite,
  myCollections,
  onLike,
  onRemix,
  onTag,
  onCollect,
}: {
  sprite: SpriteItem;
  myCollections: CollectionItem[];
  onLike: (sprite: SpriteItem) => void;
  onRemix: (sprite: SpriteItem) => void;
  onTag: (tag: string) => void;
  onCollect: (sprite: SpriteItem, collectionId: string | "new") => void;
}) {
  return (
    <Card className="gap-2.5 border-2 py-3">
      <CardContent className="flex flex-col items-center gap-2.5 px-3">
        <RecipeCanvas
          recipe={sprite.recipe}
          pixel={Math.max(2, Math.floor(112 / sprite.recipe.size))}
          className="border"
        />
        <div className="w-full space-y-1">
          <div className="truncate text-sm font-bold" title={sprite.name}>
            {sprite.name}
          </div>
          <div className="flex items-center gap-1.5 text-xs text-muted-foreground">
            <PixelAvatar username={sprite.username} size={16} />
            <span className="truncate">@{sprite.username}</span>
            {sprite.parentId && <GitFork className="size-3 shrink-0" aria-label="remix" />}
            {sprite.model && (
              <Tip label={`generated by ${sprite.model}`}>
                <span className="flex min-w-0 items-center gap-0.5">
                  <Bot className="size-3 shrink-0" />
                  <span className="truncate">{sprite.model.split("/").pop()}</span>
                </span>
              </Tip>
            )}
          </div>
          {sprite.tags.length > 0 && (
            <div className="flex flex-wrap gap-1 pt-0.5">
              {sprite.tags.map((tag) => (
                <Badge
                  key={tag}
                  variant="outline"
                  className="cursor-pointer px-1.5 py-0 text-[10px] hover:bg-accent"
                  onClick={() => onTag(tag)}
                >
                  {tag}
                </Badge>
              ))}
            </div>
          )}
        </div>
      </CardContent>
      <CardFooter className="gap-1 px-3">
        <Button size="sm" variant={sprite.liked ? "default" : "outline"} onClick={() => onLike(sprite)}>
          <Heart className={cn("size-3.5", sprite.liked && "fill-current")} />
          {sprite.likeCount}
        </Button>
        <Tip label="remix">
          <Button size="icon-sm" variant="outline" onClick={() => onRemix(sprite)} aria-label="remix">
            <GitFork className="size-3.5" />
          </Button>
        </Tip>
        <span className="ml-auto flex gap-1">
          <DropdownMenu>
            <Tip label="add to collection">
              <DropdownMenuTrigger asChild>
                <Button size="icon-sm" variant="ghost" aria-label="add to collection">
                  <FolderPlus className="size-3.5" />
                </Button>
              </DropdownMenuTrigger>
            </Tip>
            <DropdownMenuContent align="end" className="border-2">
              <DropdownMenuLabel>add to collection</DropdownMenuLabel>
              <DropdownMenuSeparator />
              {myCollections.map((c) => (
                <DropdownMenuItem key={c.id} onClick={() => onCollect(sprite, c.id)}>
                  {c.name}
                </DropdownMenuItem>
              ))}
              <DropdownMenuItem onClick={() => onCollect(sprite, "new")}>＋ new collection…</DropdownMenuItem>
            </DropdownMenuContent>
          </DropdownMenu>
          <Tip label="open PNG">
            <Button size="icon-sm" variant="ghost" asChild>
              <a href={`/api/sprites/${sprite.id}.png?scale=8`} target="_blank" rel="noreferrer" aria-label="open PNG">
                <Download className="size-3.5" />
              </a>
            </Button>
          </Tip>
        </span>
      </CardFooter>
    </Card>
  );
}
