// Generate migrations/0003_seed.sql from the example recipes: a system user
// "bitloom" plus every example published as a real sprite with tags.
// Run: bun scripts/gen-seed.ts > migrations/0003_seed.sql

import { EXAMPLES } from "../src/engine/examples";

const SEED_USER_ID = "seed-user-bitloom";
const BASE_TS = 1753372800000; // 2026-07-24T16:00:00Z, fixed so the migration is deterministic

const TAGS: Record<string, string[]> = {
  skull: ["undead", "monster"],
  sword: ["item", "weapon"],
  potion: ["item", "consumable"],
  slime: ["monster"],
  tree: ["nature"],
  wall: ["tile"],
  key: ["item"],
  heart: ["ui"],
};

function sql(value: string): string {
  return `'${value.replace(/'/g, "''")}'`;
}

const lines: string[] = [
  "-- Seed: the example gallery published as real sprites by a system user.",
  "-- Generated by scripts/gen-seed.ts — regenerate rather than editing by hand.",
  "",
  `INSERT INTO "user" ("id", "name", "email", "emailVerified", "image", "createdAt", "updatedAt", "username", "displayUsername")`,
  `VALUES (${sql(SEED_USER_ID)}, 'spriteloom', 'seed@spriteloom.invalid', 1, NULL, '2026-07-24T00:00:00.000Z', '2026-07-24T00:00:00.000Z', 'spriteloom', 'spriteloom');`,
  "",
];

EXAMPLES.forEach((recipe, i) => {
  const name = recipe.name!;
  const id = `seed-sprite-${name}`;
  const tags = [...(TAGS[name] ?? []), `${recipe.size}x${recipe.size}`];
  lines.push(
    `INSERT INTO "sprite" ("id", "userId", "name", "recipe", "parentId", "likeCount", "createdAt", "tags")`,
    `VALUES (${sql(id)}, ${sql(SEED_USER_ID)}, ${sql(name)}, ${sql(JSON.stringify(recipe))}, NULL, 0, ${BASE_TS + i * 1000}, ${sql(JSON.stringify(tags))});`,
  );
  for (const tag of tags) {
    lines.push(`INSERT INTO "sprite_tag" ("tag", "spriteId") VALUES (${sql(tag)}, ${sql(id)});`);
  }
  lines.push("");
});

console.log(lines.join("\n"));
